apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 5
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato-container
          image: srinivasedugutta/zomato
          ports:
            - containerPort: 3000  # Your app runs on port 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  selector:
    app: zomato
  ports:
    - protocol: TCP
      port: 80          # External port exposed to the world
      targetPort: 3000  # App container listens on 3000
  type: LoadBalancer
